services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniswap-router-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - uniswap-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  uniswap-network:
    driver: bridge 